In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("Final_Dataset_181216.csv")
df

,Restaurant_Name,Rating,Review_Count,Price,Score,Grade
0,Pagoda Inn,4.0,251,$$,70,C
1,The Dime,3.5,319,$$,93,A
2,Sushimon,4.0,192,$,91,A
3,Catch,3.5,229,$$$,96,A
4,Max City BBQ,4.0,818,$$,94,A
5,Pho Family Restaurant,4.0,101,$,94,A
6,Commonwealth Restaurant,4.5,770,$$$,93,A
7,Emon,4.0,132,$$,90,B
8,Tacos El Zorro,4.0,78,$,93,A
9,Agoura Hills Numero Uno,4.0,112,$$,97,A
10,C&O Trattoria,4.0,3093,$$,95,A
11,The Great Caesar Banquet Hall,4.5,65,na,93,A
12,Cal Mare,4.0,190,$$$,90,B
13,La Favorita Bakery,3.0,55,$,91,A
14,Hudson House,4.0,967,$$,90,B
15,Boiling Point,3.5,609,$$,90,B
16,La Indiana Restaurant,4.0,94,$,94,A
17,Cha Cha Chicken,4.0,1920,$$,92,A
18,Rainbow Donuts,4.0,109,$,90,B
19,Red Iron Mongolian BBQ,4.0,53,$,91,A
20,Torrance City Farmers Market,4.5,362,$$,92,A
21,Rinaldi's of Redondo,3.0,118,$,90,B
22,Park's BBQ,4.0,1534,$$$,90,B
23,India's Grill,4.0,562,$$,90,B
24,Rinjani,4.5,107,$$,95,A
25,Green Cottage Restaurant - Tarzana,4.0,204,$$,92,A
26,Cassia,4.0,906,$$$,94,A
27,Arashi Sushi,4.0,679,$$,92,A
28,Aroma Spa & Sports,3.5,116,$$,87,B
29,Taihei,4.0,437,$$,92,A
...,...,...,...,...,...,...
3705,Loteria Grill,3.5,926,$$,98,A
3706,Los Angeles Zoo & Botanical Gardens,3.5,1419,na,95,A
3707,Taco Ranch,4.0,103,$,95,A
3708,Mahan Indian Restaurant,4.0,499,$$,92,A
3709,We Want Tacos Cafe,4.0,60,na,84,B
3710,Baja Fresh,3.0,68,$,93,A
3711,Little China,3.5,173,$,80,C
3712,Tacos Tu Madre,4.0,947,$,96,A
3713,Mateo's Ice Cream & Fruit Bars,4.5,269,$,94,A
3714,Cafe Dulce,4.0,2025,$,70,C
3715,Pazzo Gelato,4.5,876,$,92,A
3716,Bahia Ensenada Grill,3.0,51,$,95,A
3717,Tender Trap,4.5,60,$,94,A
3718,Bottega Louie,4.0,15784,$$,95,A
3719,La Favorita Bakery,3.5,77,$,92,A
3720,Rainbow Acres Natural Foods,4.0,194,$,93,A
3721,La Carreta,4.0,154,$,94,A
3722,Slusheeland,4.5,311,$,94,A
3723,Uncle John's Cafe,4.0,581,$,96,A
3724,City of Hope,3.5,187,na,97,A
3725,Rainbow Sushi & Teriyaki,4.0,107,$,92,A
3726,Olive Terrace Bar and Grill,4.0,546,$$,90,B
3727,Famous Burgers,3.0,99,$,95,A
3728,Kobawoo House,4.5,1074,$$,81,B
3729,Fiesta Martin Mexican Grill,4.0,769,$$,94,A
3730,Dragon Bakery,5.0,55,$$,98,A
3731,Quickly,3.5,198,$,90,B
3732,Caffe Latte,4.0,188,$$,95,A
3733,Settebello Pizzeria Napoletana,3.5,319,$$,96,A
3734,Juanito's Place,4.0,55,$,90,B