In [8]:

# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import time
import datetime
import pprint
import csv
from datetime import datetime

In [9]:
county_data_file= 'data/LOS_ANGELES_COUNTY_RESTAURANT_AND_MARKET_INSPECTIONS.csv'

In [10]:
county_data_file=pd.read_csv(county_data_file)
county_data_file.head()

,ACTIVITY DATE,OWNER ID,OWNER NAME,FACILITY ID,FACILITY NAME,RECORD ID,PROGRAM NAME,PROGRAM STATUS,PROGRAM ELEMENT (PE),PE DESCRIPTION,FACILITY ADDRESS,FACILITY CITY,FACILITY STATE,FACILITY ZIP,SERVICE CODE,SERVICE DESCRIPTION,SCORE,GRADE,SERIAL NUMBER,EMPLOYEE ID
0,06/22/2016,OW0185247,TB AZUSA,FA0179753,TEA BAR,PR0173413,TEA BAR,ACTIVE,1635,RESTAURANT (31-60) SEATS HIGH RISK,954 E ALOSTA AVE,AZUSA,CA,91702,1,ROUTINE INSPECTION,93,A,DAC6YRJ7D,EE0000742
1,09/07/2016,OW0235635,"2015, INC",FA0239319,SHEFA,PR0187286,SHEFA,ACTIVE,1632,RESTAURANT (0-30) SEATS HIGH RISK,7275 MELROSE AVE,LOS ANGELES,CA,90046,1,ROUTINE INSPECTION,90,A,DAKU06F5Y,EE0000951
2,09/09/2016,OW0018013,JSG CORP,FA0071154,SUBWAY,PR0015184,SUBWAY,ACTIVE,1631,RESTAURANT (0-30) SEATS MODERATE RISK,28788 THE OLD RD,VALENCIA,CA,91355,1,ROUTINE INSPECTION,98,A,DAFS03QYK,EE0000735
3,04/01/2016,OW0001761,ADVANCED FRESH CONCEPTS FRANCHISE CORP,FA0144494,AFC SUSHI @ VONS #3138,PR0130557,AFC SUSHI @ VONS #3138,ACTIVE,1632,RESTAURANT (0-30) SEATS HIGH RISK,16550 SOLEDAD CANYON RD,CANYON COUNTRY,CA,91387-3215,1,ROUTINE INSPECTION,99,A,DAJ8A0PDB,EE0000735
4,04/01/2016,OW0002023,ALBERTANO'S AUTHENTIC MEXICA,FA0005693,ALBERTS MEXICAN FOOD,PR0040352,ALBERTS MEXICAN FOOD,INACTIVE,1632,RESTAURANT (0-30) SEATS HIGH RISK,2355 PECK RD,SOUTH EL MONTE,CA,91733,1,ROUTINE INSPECTION,92,A,DA6E75RM0,EE0000842

In [11]:
county_data_file.count()

ACTIVITY DATE           199950
OWNER ID                199950
OWNER NAME              199950
FACILITY ID             199950
FACILITY NAME           199950
RECORD ID               199950
PROGRAM NAME            199950
PROGRAM STATUS          199950
PROGRAM ELEMENT (PE)    199950
PE DESCRIPTION          199950
FACILITY ADDRESS        199950
FACILITY CITY           199950
FACILITY STATE          199950
FACILITY ZIP            199950
SERVICE CODE            199950
SERVICE DESCRIPTION     199950
SCORE                   199950
GRADE                   199895
SERIAL NUMBER           199950
EMPLOYEE ID             199950
dtype: int64

In [16]:
columns=['ACTIVITY DATE','FACILITY ID','FACILITY NAME','PROGRAM STATUS','FACILITY ADDRESS','FACILITY CITY','FACILITY ZIP','SCORE','GRADE']
new_data_county=county_data_file[columns]
new_data_county['ACTIVITY DATE']=pd.to_datetime(new_data_county['ACTIVITY DATE'])
new_data_county.head()

/Users/anjalivardhan/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

,ACTIVITY DATE,FACILITY ID,FACILITY NAME,PROGRAM STATUS,FACILITY ADDRESS,FACILITY CITY,FACILITY ZIP,SCORE,GRADE
0,2016-06-22,FA0179753,TEA BAR,ACTIVE,954 E ALOSTA AVE,AZUSA,91702,93,A
1,2016-09-07,FA0239319,SHEFA,ACTIVE,7275 MELROSE AVE,LOS ANGELES,90046,90,A
2,2016-09-09,FA0071154,SUBWAY,ACTIVE,28788 THE OLD RD,VALENCIA,91355,98,A
3,2016-04-01,FA0144494,AFC SUSHI @ VONS #3138,ACTIVE,16550 SOLEDAD CANYON RD,CANYON COUNTRY,91387-3215,99,A
4,2016-04-01,FA0005693,ALBERTS MEXICAN FOOD,INACTIVE,2355 PECK RD,SOUTH EL MONTE,91733,92,A

In [18]:
new_data_county.sort_values(by=["ACTIVITY DATE","FACILITY ID","FACILITY ADDRESS"],inplace = True,ascending=True)
new_data_county.head()

/Users/anjalivardhan/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

,ACTIVITY DATE,FACILITY ID,FACILITY NAME,PROGRAM STATUS,FACILITY ADDRESS,FACILITY CITY,FACILITY ZIP,SCORE,GRADE
94,2016-04-01,FA0002213,RANCHITO MILLAN,ACTIVE,5803 S SOTO ST,HUNTINGTON PARK,90255,94,A
12,2016-04-01,FA0004764,BALDWIN OIL,ACTIVE,13758 LOS ANGELES ST,BALDWIN PARK,91706,98,A
14,2016-04-01,FA0004876,BANQUET KITCHEN,ACTIVE,135 N GRAND AVE,LOS ANGELES,90012,97,A
5,2016-04-01,FA0005575,ALL STAR PARK COMPANY,INACTIVE,17911 S BELLFLOWER BLVD,BELLFLOWER,90706,91,A
17,2016-04-01,FA0005633,BIG O LIQUIOR,INACTIVE,4626 S VERMONT AVE,LOS ANGELES,90037,95,A

In [21]:
unique_county_data = new_data_county.drop_duplicates(subset = ['FACILITY ID'], keep = 'last')
unique_county_data.count()

ACTIVITY DATE       44581
FACILITY ID         44581
FACILITY NAME       44581
PROGRAM STATUS      44581
FACILITY ADDRESS    44581
FACILITY CITY       44581
FACILITY ZIP        44581
SCORE               44581
GRADE               44563
dtype: int64

In [22]:
unique_county_data = unique_county_data.loc[(unique_county_data['PROGRAM STATUS'] != "INACTIVE"),:]
unique_county_data.count()

ACTIVITY DATE       36474
FACILITY ID         36474
FACILITY NAME       36474
PROGRAM STATUS      36474
FACILITY ADDRESS    36474
FACILITY CITY       36474
FACILITY ZIP        36474
SCORE               36474
GRADE               36462
dtype: int64

In [23]:
unique_county_data = unique_county_data.dropna(how='any')
unique_county_data.count()

ACTIVITY DATE       36462
FACILITY ID         36462
FACILITY NAME       36462
PROGRAM STATUS      36462
FACILITY ADDRESS    36462
FACILITY CITY       36462
FACILITY ZIP        36462
SCORE               36462
GRADE               36462
dtype: int64